import type { Metadata } from "next";
import { Rammetto_One, Lexend } from "next/font/google";
import "./globals.css";
import Container from "./components/container";

const lexend = Lexend({ subsets: ["latin"] });
const Rammetto = Rammetto_One({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          lexend.className +
          " overscroll-y-none bg-gray-950 antialiased selection:bg-violet-600/90 selection:text-white "
        }
      >
        <Container>{children}</Container>
      </body>
    </html>
  );
}
